import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../model/word.dart';

final wordsViewModelProvider = StateNotifierProvider<WordsViewModel, List<Word>>((ref) {
  return WordsViewModel();
});

class WordsViewModel extends StateNotifier<List<Word>> {
  WordsViewModel() : super([]);

  // ダミーデータの作成
  final List<Word> dummyData = [
    Word(
      id: "1",
      number: "001",
      points: 0,
      english: "example",
      japanese1: "例",
      japanese2: "実例",
      exampleSentenceEnglish: "This is an example.",
      exampleSentenceJapanese: "これは例です。",
      conjugation1: "exampled",
      conjugation2: "exampled",
      prototypePronunciation: "ɪɡˈzæmpəl",
      conjugation1Pronunciation: "ɪɡˈzæmpəld",
      conjugation2Pronunciation: "ɪɡˈzæmpəld",
      withSetEnglish: "sample",
      withSetJapanese1: "見本",
      withSetJapanese2: "サンプル",
      pronunciationKana: "イグザンプル",
      pronunciationSymbol: "ɪɡˈzæmpəl",
      polysemy1: "実例",
      polysemy2: "見本",
      silent: false,
      partOfSpeechNumber: 1,
      primarySchool1: true,
      primarySchool2: false,
      primarySchool3: false,
      primarySchool4: false,
      primarySchool5: false,
      juniorHighSchool1: true,
      juniorHighSchool2: false,
      juniorHighSchool3: false,
      juniorHighSchool4: false,
      juniorHighSchool5: false,
      highSchool1: false,
      highSchool2: false,
      highSchool3: false,
      highSchool4: false,
      highSchool5: false,
      university1: false,
      university2: false,
      university3: false,
      university4: false,
      university5: false,
      toeic1: true,
      toeic2: false,
      toeic3: false,
      toeic4: false,
      toeic5: false,
      eiken1: false,
      eiken2: false,
      eiken3: true,
      eiken4: false,
      eiken5: false,
      eiken6: false,
      eiken7: false,
      toefl1: false,
      toefl2: false,
      toefl3: false,
      toefl4: false,
      toefl5: false,
      irregularVerb1: false,
      irregularVerb2: false,
      irregularVerb3: false,
      idioms1: false,
      idioms2: false,
      idioms3: false,
      withSet1: true,
      withSet2: false,
      withSet3: false,
      easyToMistake1: false,
      easyToMistake2: false,
      easyToMistake3: false,
      pronunciationAttention1: false,
      pronunciationAttention2: false,
      pronunciationAttention3: false,
      polysemy1Flag: true,
      polysemy2Flag: true,
      polysemy3Flag: false,
      concern1: false,
      concern2: false,
      concern3: false,
      animal: false,
      plant: false,
      bodyToFace: false,
      food: false,
      dailyLife: true,
      housesAndFacilities: false,
      other: false,
      remembered: false,
      catStampCount: 0,
      freePaidKubun: 0,
      juniorHighSchoolVerb: true,
      juniorHighSchoolAdjectives: false,
      juniorHighSchoolAdverb: false,
      highSchoolVerb: false,
      highSchoolAdjectives: false,
      highSchoolAdverb: false,
      highSchoolNoun: true,
    ),
    Word(
      id: "2",
      number: "002",
      points: 5,
      english: "achieve",
      japanese1: "達成する",
      japanese2: "成し遂げる",
      exampleSentenceEnglish: "She achieved her goal.",
      exampleSentenceJapanese: "彼女は目標を達成した。",
      conjugation1: "achieved",
      conjugation2: "achieved",
      prototypePronunciation: "əˈtʃiːv",
      conjugation1Pronunciation: "əˈtʃiːvd",
      conjugation2Pronunciation: "əˈtʃiːvd",
      withSetEnglish: "accomplish",
      withSetJapanese1: "達成する",
      withSetJapanese2: "完遂する",
      pronunciationKana: "アチーブ",
      pronunciationSymbol: "əˈtʃiːv",
      polysemy1: "到達する",
      polysemy2: "獲得する",
      silent: false,
      partOfSpeechNumber: 1,
      primarySchool1: false,
      primarySchool2: false,
      primarySchool3: false,
      primarySchool4: false,
      primarySchool5: false,
      juniorHighSchool1: false,
      juniorHighSchool2: true,
      juniorHighSchool3: false,
      juniorHighSchool4: false,
      juniorHighSchool5: false,
      highSchool1: true,
      highSchool2: false,
      highSchool3: false,
      highSchool4: false,
      highSchool5: false,
      university1: false,
      university2: false,
      university3: false,
      university4: false,
      university5: false,
      toeic1: true,
      toeic2: true,
      toeic3: false,
      toeic4: false,
      toeic5: false,
      eiken1: false,
      eiken2: true,
      eiken3: false,
      eiken4: false,
      eiken5: false,
      eiken6: false,
      eiken7: false,
      toefl1: true,
      toefl2: false,
      toefl3: false,
      toefl4: false,
      toefl5: false,
      irregularVerb1: false,
      irregularVerb2: false,
      irregularVerb3: false,
      idioms1: false,
      idioms2: false,
      idioms3: false,
      withSet1: true,
      withSet2: true,
      withSet3: false,
      easyToMistake1: false,
      easyToMistake2: false,
      easyToMistake3: false,
      pronunciationAttention1: false,
      pronunciationAttention2: false,
      pronunciationAttention3: false,
      polysemy1Flag: true,
      polysemy2Flag: true,
      polysemy3Flag: false,
      concern1: false,
      concern2: false,
      concern3: false,
      animal: false,
      plant: false,
      bodyToFace: false,
      food: false,
      dailyLife: false,
      housesAndFacilities: false,
      other: true,
      remembered: true,
      catStampCount: 2,
      freePaidKubun: 1,
      juniorHighSchoolVerb: true,
      juniorHighSchoolAdjectives: false,
      juniorHighSchoolAdverb: false,
      highSchoolVerb: true,
      highSchoolAdjectives: false,
      highSchoolAdverb: false,
      highSchoolNoun: false,
    ),
    Word(
      id: "3",
      number: "003",
      points: 3,
      english: "brave",
      japanese1: "勇敢な",
      japanese2: "勇気のある",
      exampleSentenceEnglish: "He was brave enough to face his fears.",
      exampleSentenceJapanese: "彼は恐怖に立ち向かうほど勇敢だった。",
      conjugation1: "",
      conjugation2: "",
      prototypePronunciation: "breɪv",
      conjugation1Pronunciation: "",
      conjugation2Pronunciation: "",
      withSetEnglish: "courage",
      withSetJapanese1: "勇気",
      withSetJapanese2: "度胸",
      pronunciationKana: "ブレイブ",
      pronunciationSymbol: "breɪv",
      polysemy1: "立派な",
      polysemy2: "賞賛に値する",
      silent: false,
      partOfSpeechNumber: 3,
      primarySchool1: false,
      primarySchool2: true,
      primarySchool3: false,
      primarySchool4: false,
      primarySchool5: false,
      juniorHighSchool1: true,
      juniorHighSchool2: false,
      juniorHighSchool3: false,
      juniorHighSchool4: false,
      juniorHighSchool5: false,
      highSchool1: false,
      highSchool2: false,
      highSchool3: false,
      highSchool4: false,
      highSchool5: false,
      university1: false,
      university2: false,
      university3: false,
      university4: false,
      university5: false,
      toeic1: false,
      toeic2: false,
      toeic3: true,
      toeic4: false,
      toeic5: false,
      eiken1: false,
      eiken2: false,
      eiken3: true,
      eiken4: false,
      eiken5: false,
      eiken6: false,
      eiken7: false,
      toefl1: false,
      toefl2: false,
      toefl3: false,
      toefl4: false,
      toefl5: false,
      irregularVerb1: false,
      irregularVerb2: false,
      irregularVerb3: false,
      idioms1: false,
      idioms2: false,
      idioms3: false,
      withSet1: true,
      withSet2: false,
      withSet3: false,
      easyToMistake1: false,
      easyToMistake2: false,
      easyToMistake3: false,
      pronunciationAttention1: false,
      pronunciationAttention2: false,
      pronunciationAttention3: false,
      polysemy1Flag: true,
      polysemy2Flag: true,
      polysemy3Flag: false,
      concern1: false,
      concern2: false,
      concern3: false,
      animal: false,
      plant: false,
      bodyToFace: false,
      food: false,
      dailyLife: false,
      housesAndFacilities: false,
      other: true,
      remembered: true,
      catStampCount: 1,
      freePaidKubun: 0,
      juniorHighSchoolVerb: false,
      juniorHighSchoolAdjectives: true,
      juniorHighSchoolAdverb: false,
      highSchoolVerb: false,
      highSchoolAdjectives: false,
      highSchoolAdverb: false,
      highSchoolNoun: false,
    ),
  ];
  void initWords() {
    state = dummyData;
  }
  void setWords(List<Word> words) {
    state = words;
  }

  void addWord(Word word) {
    state = [...state, word];
  }

  void updateWord(Word word) {
    final index = state.indexWhere((element) => element.id == word.id);
    if (index != -1) {
      state = [...state]..setAll(index, [word]);
    }
  }

  void deleteWord(Word word) {
    state = state.where((element) => element.id != word.id).toList();
  }
}