// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'word.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Word _$$_WordFromJson(Map<String, dynamic> json) => _$_Word(
      id: json['id'] as String,
      number: json['number'] as String,
      points: json['points'] as int,
      english: json['english'] as String,
      japanese1: json['japanese1'] as String,
      japanese2: json['japanese2'] as String,
      exampleSentenceEnglish: json['exampleSentenceEnglish'] as String,
      exampleSentenceJapanese: json['exampleSentenceJapanese'] as String,
      conjugation1: json['conjugation1'] as String,
      conjugation2: json['conjugation2'] as String,
      prototypePronunciation: json['prototypePronunciation'] as String,
      conjugation1Pronunciation: json['conjugation1Pronunciation'] as String,
      conjugation2Pronunciation: json['conjugation2Pronunciation'] as String,
      withSetEnglish: json['withSetEnglish'] as String,
      withSetJapanese1: json['withSetJapanese1'] as String,
      withSetJapanese2: json['withSetJapanese2'] as String,
      pronunciationKana: json['pronunciationKana'] as String,
      pronunciationSymbol: json['pronunciationSymbol'] as String,
      polysemy1: json['polysemy1'] as String,
      polysemy2: json['polysemy2'] as String,
      silent: json['silent'] as bool,
      partOfSpeechNumber: json['partOfSpeechNumber'] as int,
      primarySchool1: json['primarySchool1'] as bool,
      primarySchool2: json['primarySchool2'] as bool,
      primarySchool3: json['primarySchool3'] as bool,
      primarySchool4: json['primarySchool4'] as bool,
      primarySchool5: json['primarySchool5'] as bool,
      juniorHighSchool1: json['juniorHighSchool1'] as bool,
      juniorHighSchool2: json['juniorHighSchool2'] as bool,
      juniorHighSchool3: json['juniorHighSchool3'] as bool,
      juniorHighSchool4: json['juniorHighSchool4'] as bool,
      juniorHighSchool5: json['juniorHighSchool5'] as bool,
      highSchool1: json['highSchool1'] as bool,
      highSchool2: json['highSchool2'] as bool,
      highSchool3: json['highSchool3'] as bool,
      highSchool4: json['highSchool4'] as bool,
      highSchool5: json['highSchool5'] as bool,
      university1: json['university1'] as bool,
      university2: json['university2'] as bool,
      university3: json['university3'] as bool,
      university4: json['university4'] as bool,
      university5: json['university5'] as bool,
      toeic1: json['toeic1'] as bool,
      toeic2: json['toeic2'] as bool,
      toeic3: json['toeic3'] as bool,
      toeic4: json['toeic4'] as bool,
      toeic5: json['toeic5'] as bool,
      eiken1: json['eiken1'] as bool,
      eiken2: json['eiken2'] as bool,
      eiken3: json['eiken3'] as bool,
      eiken4: json['eiken4'] as bool,
      eiken5: json['eiken5'] as bool,
      eiken6: json['eiken6'] as bool,
      eiken7: json['eiken7'] as bool,
      toefl1: json['toefl1'] as bool,
      toefl2: json['toefl2'] as bool,
      toefl3: json['toefl3'] as bool,
      toefl4: json['toefl4'] as bool,
      toefl5: json['toefl5'] as bool,
      irregularVerb1: json['irregularVerb1'] as bool,
      irregularVerb2: json['irregularVerb2'] as bool,
      irregularVerb3: json['irregularVerb3'] as bool,
      idioms1: json['idioms1'] as bool,
      idioms2: json['idioms2'] as bool,
      idioms3: json['idioms3'] as bool,
      withSet1: json['withSet1'] as bool,
      withSet2: json['withSet2'] as bool,
      withSet3: json['withSet3'] as bool,
      easyToMistake1: json['easyToMistake1'] as bool,
      easyToMistake2: json['easyToMistake2'] as bool,
      easyToMistake3: json['easyToMistake3'] as bool,
      pronunciationAttention1: json['pronunciationAttention1'] as bool,
      pronunciationAttention2: json['pronunciationAttention2'] as bool,
      pronunciationAttention3: json['pronunciationAttention3'] as bool,
      polysemy1Flag: json['polysemy1Flag'] as bool,
      polysemy2Flag: json['polysemy2Flag'] as bool,
      polysemy3Flag: json['polysemy3Flag'] as bool,
      concern1: json['concern1'] as bool,
      concern2: json['concern2'] as bool,
      concern3: json['concern3'] as bool,
      animal: json['animal'] as bool,
      plant: json['plant'] as bool,
      bodyToFace: json['bodyToFace'] as bool,
      food: json['food'] as bool,
      dailyLife: json['dailyLife'] as bool,
      housesAndFacilities: json['housesAndFacilities'] as bool,
      other: json['other'] as bool,
      remembered: json['remembered'] as bool,
      catStampCount: json['catStampCount'] as int,
      freePaidKubun: json['freePaidKubun'] as int,
      juniorHighSchoolVerb: json['juniorHighSchoolVerb'] as bool,
      juniorHighSchoolAdjectives: json['juniorHighSchoolAdjectives'] as bool,
      juniorHighSchoolAdverb: json['juniorHighSchoolAdverb'] as bool,
      highSchoolVerb: json['highSchoolVerb'] as bool,
      highSchoolAdjectives: json['highSchoolAdjectives'] as bool,
      highSchoolAdverb: json['highSchoolAdverb'] as bool,
      highSchoolNoun: json['highSchoolNoun'] as bool,
    );

Map<String, dynamic> _$$_WordToJson(_$_Word instance) => <String, dynamic>{
      'id': instance.id,
      'number': instance.number,
      'points': instance.points,
      'english': instance.english,
      'japanese1': instance.japanese1,
      'japanese2': instance.japanese2,
      'exampleSentenceEnglish': instance.exampleSentenceEnglish,
      'exampleSentenceJapanese': instance.exampleSentenceJapanese,
      'conjugation1': instance.conjugation1,
      'conjugation2': instance.conjugation2,
      'prototypePronunciation': instance.prototypePronunciation,
      'conjugation1Pronunciation': instance.conjugation1Pronunciation,
      'conjugation2Pronunciation': instance.conjugation2Pronunciation,
      'withSetEnglish': instance.withSetEnglish,
      'withSetJapanese1': instance.withSetJapanese1,
      'withSetJapanese2': instance.withSetJapanese2,
      'pronunciationKana': instance.pronunciationKana,
      'pronunciationSymbol': instance.pronunciationSymbol,
      'polysemy1': instance.polysemy1,
      'polysemy2': instance.polysemy2,
      'silent': instance.silent,
      'partOfSpeechNumber': instance.partOfSpeechNumber,
      'primarySchool1': instance.primarySchool1,
      'primarySchool2': instance.primarySchool2,
      'primarySchool3': instance.primarySchool3,
      'primarySchool4': instance.primarySchool4,
      'primarySchool5': instance.primarySchool5,
      'juniorHighSchool1': instance.juniorHighSchool1,
      'juniorHighSchool2': instance.juniorHighSchool2,
      'juniorHighSchool3': instance.juniorHighSchool3,
      'juniorHighSchool4': instance.juniorHighSchool4,
      'juniorHighSchool5': instance.juniorHighSchool5,
      'highSchool1': instance.highSchool1,
      'highSchool2': instance.highSchool2,
      'highSchool3': instance.highSchool3,
      'highSchool4': instance.highSchool4,
      'highSchool5': instance.highSchool5,
      'university1': instance.university1,
      'university2': instance.university2,
      'university3': instance.university3,
      'university4': instance.university4,
      'university5': instance.university5,
      'toeic1': instance.toeic1,
      'toeic2': instance.toeic2,
      'toeic3': instance.toeic3,
      'toeic4': instance.toeic4,
      'toeic5': instance.toeic5,
      'eiken1': instance.eiken1,
      'eiken2': instance.eiken2,
      'eiken3': instance.eiken3,
      'eiken4': instance.eiken4,
      'eiken5': instance.eiken5,
      'eiken6': instance.eiken6,
      'eiken7': instance.eiken7,
      'toefl1': instance.toefl1,
      'toefl2': instance.toefl2,
      'toefl3': instance.toefl3,
      'toefl4': instance.toefl4,
      'toefl5': instance.toefl5,
      'irregularVerb1': instance.irregularVerb1,
      'irregularVerb2': instance.irregularVerb2,
      'irregularVerb3': instance.irregularVerb3,
      'idioms1': instance.idioms1,
      'idioms2': instance.idioms2,
      'idioms3': instance.idioms3,
      'withSet1': instance.withSet1,
      'withSet2': instance.withSet2,
      'withSet3': instance.withSet3,
      'easyToMistake1': instance.easyToMistake1,
      'easyToMistake2': instance.easyToMistake2,
      'easyToMistake3': instance.easyToMistake3,
      'pronunciationAttention1': instance.pronunciationAttention1,
      'pronunciationAttention2': instance.pronunciationAttention2,
      'pronunciationAttention3': instance.pronunciationAttention3,
      'polysemy1Flag': instance.polysemy1Flag,
      'polysemy2Flag': instance.polysemy2Flag,
      'polysemy3Flag': instance.polysemy3Flag,
      'concern1': instance.concern1,
      'concern2': instance.concern2,
      'concern3': instance.concern3,
      'animal': instance.animal,
      'plant': instance.plant,
      'bodyToFace': instance.bodyToFace,
      'food': instance.food,
      'dailyLife': instance.dailyLife,
      'housesAndFacilities': instance.housesAndFacilities,
      'other': instance.other,
      'remembered': instance.remembered,
      'catStampCount': instance.catStampCount,
      'freePaidKubun': instance.freePaidKubun,
      'juniorHighSchoolVerb': instance.juniorHighSchoolVerb,
      'juniorHighSchoolAdjectives': instance.juniorHighSchoolAdjectives,
      'juniorHighSchoolAdverb': instance.juniorHighSchoolAdverb,
      'highSchoolVerb': instance.highSchoolVerb,
      'highSchoolAdjectives': instance.highSchoolAdjectives,
      'highSchoolAdverb': instance.highSchoolAdverb,
      'highSchoolNoun': instance.highSchoolNoun,
    };
