import 'package:freezed_annotation/freezed_annotation.dart';
/// 単語帳情報クラス

part 'word.freezed.dart';
part 'word.g.dart';

@freezed
class Word with _$Word {
  const factory Word({
    required String id,
    required String number,
    required int points,
    required String english,
    required String japanese1,
    required String japanese2,
    required String exampleSentenceEnglish,
    required String exampleSentenceJapanese,
    required String conjugation1,
    required String conjugation2,
    required String prototypePronunciation,
    required String conjugation1Pronunciation,
    required String conjugation2Pronunciation,
    required String withSetEnglish,
    required String withSetJapanese1,
    required String withSetJapanese2,
    required String pronunciationKana,
    required String pronunciationSymbol,
    required String polysemy1,
    required String polysemy2,
    required bool silent,
    required int partOfSpeechNumber,
    // 学校レベルと試験レベルのフィールド
    required bool primarySchool1,
    required bool primarySchool2,
    required bool primarySchool3,
    required bool primarySchool4,
    required bool primarySchool5,
    required bool juniorHighSchool1,
    required bool juniorHighSchool2,
    required bool juniorHighSchool3,
    required bool juniorHighSchool4,
    required bool juniorHighSchool5,
    required bool highSchool1,
    required bool highSchool2,
    required bool highSchool3,
    required bool highSchool4,
    required bool highSchool5,
    required bool university1,
    required bool university2,
    required bool university3,
    required bool university4,
    required bool university5,
    required bool toeic1,
    required bool toeic2,
    required bool toeic3,
    required bool toeic4,
    required bool toeic5,
    required bool eiken1,
    required bool eiken2,
    required bool eiken3,
    required bool eiken4,
    required bool eiken5,
    required bool eiken6,
    required bool eiken7,
    required bool toefl1,
    required bool toefl2,
    required bool toefl3,
    required bool toefl4,
    required bool toefl5,
    required bool irregularVerb1,
    required bool irregularVerb2,
    required bool irregularVerb3,
    required bool idioms1,
    required bool idioms2,
    required bool idioms3,
    required bool withSet1,
    required bool withSet2,
    required bool withSet3,
    required bool easyToMistake1,
    required bool easyToMistake2,
    required bool easyToMistake3,
    required bool pronunciationAttention1,
    required bool pronunciationAttention2,
    required bool pronunciationAttention3,
    required bool polysemy1Flag,
    required bool polysemy2Flag,
    required bool polysemy3Flag,
    required bool concern1,
    required bool concern2,
    required bool concern3,
    required bool animal,
    required bool plant,
    required bool bodyToFace,
    required bool food,
    required bool dailyLife,
    required bool housesAndFacilities,
    required bool other,
    required bool remembered,
    required int catStampCount,
    required int freePaidKubun,
    required bool juniorHighSchoolVerb,
    required bool juniorHighSchoolAdjectives,
    required bool juniorHighSchoolAdverb,
    required bool highSchoolVerb,
    required bool highSchoolAdjectives,
    required bool highSchoolAdverb,
    required bool highSchoolNoun,
}) = _Word;

  factory Word.fromJson(Map<String, dynamic> json) => _$WordFromJson(json);
}